name: Config Generator
on: workflow_dispatch
jobs:
  config-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: build other repo
        run: echo "building   $USER"
